#!/usr/bin/env python3
"""Regenerate tvision-sources.gypi -- the list of Turbo Vision's .cpp files.

gyp has no globbing. It has `<!@(command)` expansion, which would let
binding.gyp shell out to `find`, and that is exactly what must not happen: a
published package's binding.gyp runs on the *user's* machine, where the shell
may be something else and on Windows is nothing at all. So the list is
committed, and this script is what keeps it honest.

The rule is `source/CMakeLists.txt`'s, so that moving the submodule pin cannot
quietly change what gets compiled:

    file(GLOB_RECURSE TVSOURCE "${CMAKE_CURRENT_LIST_DIR}/*/*.cpp")
    list(REMOVE_ITEM TVSOURCE ".../tvision/geninc.cpp")

Every file, both directories, minus the one generator. Nothing is filtered by
platform here because Turbo Vision does not filter by platform either --
`win32con.cpp` is `#ifdef _WIN32` from its second line to its last, and
compiles to an empty object everywhere else.

`--check` exits non-zero if the file on disk is not what this would write,
which is what `devbox run check` calls.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
SOURCE = os.path.join(PKG, "tvision", "source")
GYPI = os.path.join(PKG, "tvision-sources.gypi")

EXCLUDE = {"tvision/geninc.cpp"}


def sources():
    """Every .cpp under source/*/, relative to the package directory."""
    found = []
    for sub in sorted(os.listdir(SOURCE)):
        d = os.path.join(SOURCE, sub)
        if not os.path.isdir(d):
            continue
        for root, dirs, files in os.walk(d):
            dirs.sort()
            for name in sorted(files):
                if not name.endswith(".cpp"):
                    continue
                rel = os.path.relpath(os.path.join(root, name), SOURCE)
                if rel.replace(os.sep, "/") in EXCLUDE:
                    continue
                found.append("tvision/source/" + rel.replace(os.sep, "/"))
    return found


def render(files):
    lines = [
        "# Generated by scripts/gen-tvision-sources.py -- do not edit.",
        "# Turbo Vision's own sources, compiled into the addon. Regenerate after",
        "# moving the submodule pin; `devbox run check` fails if this is stale.",
        "{",
        '  "variables": {',
        '    "tvision_sources": [',
    ]
    lines += ['      "%s",' % f for f in files]
    lines += ["    ],", "  },", "}", ""]
    return "\n".join(lines)


def main():
    if not os.path.isdir(SOURCE):
        print("gen-tvision-sources: no %s -- is the submodule checked out?"
              % SOURCE, file=sys.stderr)
        return 2

    want = render(sources())

    if "--check" in sys.argv:
        try:
            with open(GYPI, encoding="utf-8") as f:
                have = f.read()
        except FileNotFoundError:
            have = None
        if have != want:
            print("tvision-sources.gypi is stale -- run "
                  "tvision-node/scripts/gen-tvision-sources.py", file=sys.stderr)
            return 1
        print("tvision-sources.gypi: %d sources, current"
              % len(sources()))
        return 0

    with open(GYPI, "w", encoding="utf-8") as f:
        f.write(want)
    print("tvision-sources.gypi: %d sources" % len(sources()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
